export interface Opportunity {
  id: number;
  name: string;
  category: string;
  description: string;
  amount: string;
  deadline: string;
  deadlineStatus: "open" | "est" | "closed";
  deadlineSort: string;
  eligibility: string;
  difficulty: "Easy" | "Moderate" | "Competitive";
  international: boolean;
  link: string;
  stem?: boolean;
  gradeLevels: string[];
  timeCommitment: string;
  compensated: boolean;
  isNew?: boolean;
}

export const opportunities: Opportunity[] = [
  { id: 1, name: "Loran Scholars Foundation", category: "scholarships", description: "Canada's largest undergraduate award for character, service and leadership. Includes a four-year leadership enrichment program, summer work experiences, and mentorship.", amount: "$100,000 over 4 years", deadline: "Est. 2027 — Oct 16", deadlineStatus: "est", deadlineSort: "2027-10-16", eligibility: "Canadian HS / CEGEP students, min 85% avg, citizenship or PR, born 2004–2010", difficulty: "Competitive", international: false, link: "https://www.loranscholar.ca", gradeLevels: ["Grades 11–12", "CEGEP"], timeCommitment: "Application only", compensated: true },
  { id: 2, name: "Schulich Leader Scholarships", category: "scholarships", description: "Canada's most coveted undergraduate STEM scholarships. 100 awards annually across 20 partner universities for entrepreneurial-minded students pursuing science, technology, engineering or math.", amount: "$100,000–$120,000 over 4 years", deadline: "Est. 2027 — Jan 28 / Feb 18", deadlineStatus: "est", deadlineSort: "2027-01-28", eligibility: "Canadian citizens, graduating HS/CEGEP, STEM program, school nomination required", difficulty: "Competitive", international: false, link: "https://www.schulichleaders.com", stem: true, gradeLevels: ["Grades 11–12", "CEGEP"], timeCommitment: "Application only", compensated: true },
  { id: 3, name: "TD Scholarship for Community Leadership", category: "scholarships", description: "Recognizes students across Canada who have demonstrated community leadership and a commitment to making their communities more inclusive and sustainable.", amount: "$70,000 over 4 years", deadline: "Est. 2027 — Sept 3 – Oct 22", deadlineStatus: "est", deadlineSort: "2027-09-03", eligibility: "Canadian citizens/PR, final year HS/CEGEP, min 75% avg, demonstrated community leadership", difficulty: "Competitive", international: false, link: "https://www.td.com/ca/en/personal-banking/solutions/student-banking/community-leadership-scholarship-for-canadians", gradeLevels: ["Grades 11–12", "CEGEP"], timeCommitment: "Application only", compensated: true },
  { id: 4, name: "Horatio Alger Canadian Scholarships", category: "scholarships", description: "Need-based scholarships for students who have demonstrated integrity and perseverance in overcoming adversity, with a commitment to pursuing a bachelor's degree.", amount: "Up to $10,000", deadline: "Est. 2027 — Jan 1 – Mar 31", deadlineStatus: "est", deadlineSort: "2027-01-01", eligibility: "Canadian Grade 11/12, financial need ≤$65K household income, min 70%, community involvement", difficulty: "Moderate", international: false, link: "https://horatioalger.ca", gradeLevels: ["Grades 11–12"], timeCommitment: "Application only", compensated: true },
  { id: 5, name: "Terry Fox Humanitarian Award", category: "scholarships", description: "Honours students who demonstrate the humanitarian ideals of Terry Fox through voluntary humanitarian service, courage in overcoming obstacles, and excellence in academics and civic life.", amount: "$28,000 over 4 years", deadline: "Dec 1, 2026", deadlineStatus: "open", deadlineSort: "2026-12-01", eligibility: "Canadian citizens/landed immigrants, graduating HS or completing first year CEGEP", difficulty: "Competitive", international: false, link: "https://terryfoxawards.ca", gradeLevels: ["Grades 11–12", "CEGEP"], timeCommitment: "Application only", compensated: true },
  { id: 6, name: "Canada Service Corps", category: "volunteering", description: "A national youth service program offering flexible volunteer opportunities with local and national organizations. Youth choose projects that match their interests and schedule.", amount: "Volunteer", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "Youth 15–30, Canadian citizens/PR/temporary residents, various projects across Canada", difficulty: "Easy", international: false, link: "https://www.canada.ca/en/services/youth/canada-service-corps.html", gradeLevels: ["Grades 9–10", "Grades 11–12", "CEGEP", "University"], timeCommitment: "Flexible schedule", compensated: false },
  { id: 7, name: "SickKids High School Summer Volunteer Program", category: "volunteering", description: "Intensive summer volunteer placements at The Hospital for Sick Children. Students gain hands-on experience in Hospital Support or Child Life roles in a world-class pediatric setting.", amount: "Volunteer", deadline: "Est. 2027 — Mar 11–19", deadlineStatus: "est", deadlineSort: "2027-03-11", eligibility: "Age 16+, enrolled in high school, commit to July or August (3hrs/day, Mon–Fri), Toronto", difficulty: "Moderate", international: false, link: "https://www.sickkids.ca/en/careers-volunteer/volunteering/opportunities/high-school-volunteer-opportunities", gradeLevels: ["Grades 11–12"], timeCommitment: "Summer program", compensated: false },
  { id: 8, name: "Daily Bread Food Bank", category: "volunteering", description: "Volunteer in Toronto's largest food bank. Opportunities include food sorting, warehouse order picking, kitchen prep, serving clients, and administrative support.", amount: "Volunteer", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "Age 15+, groups grades 6–12 welcome, Toronto area, no experience needed", difficulty: "Easy", international: false, link: "https://www.dailybread.ca/get-involved/volunteer", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Flexible schedule", compensated: false },
  { id: 9, name: "OFAH Foundation Virtual Volunteer Hours", category: "volunteering", description: "Earn Ontario high school volunteer hours from home through online, self-paced modules focused on conservation education and outdoor heritage.", amount: "Volunteer hours", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "Ontario high school students, age 14+, online self-paced modules", difficulty: "Easy", international: false, link: "https://www.ofahfoundation.org/learn/hs-virtual-volunteer", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Flexible schedule", compensated: false },
  { id: 10, name: "Volunteer Toronto High School Portal", category: "volunteering", description: "Ontario's leading volunteer centre connects high school students with verified community involvement opportunities for the 40-hour graduation requirement.", amount: "Volunteer hours", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "Ontario high school students, 40-hour community involvement requirement, various causes", difficulty: "Easy", international: false, link: "https://www.volunteertoronto.ca/page/HighSchoolVolunteers", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Flexible schedule", compensated: false },
  { id: 11, name: "Canadian Mathematical Olympiad", category: "competitions", description: "Canada's premier national advanced mathematics competition. Invitation-only, proof-based exam serving as the primary qualifier for Team Canada at the IMO.", amount: "$2,000 gold medal + scholarships", deadline: "Est. 2027 — Oct / Mar", deadlineStatus: "est", deadlineSort: "2027-03-01", eligibility: "Canadian citizens/PR, under 20, full-time secondary school, invitation only via COMC", difficulty: "Competitive", international: false, link: "https://cms.math.ca/competitions", stem: true, gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: true },
  { id: 12, name: "Canada-Wide Science Fair", category: "competitions", description: "Canada's largest youth STEM competition. Nearly $1 million in cash awards. Students present original research projects over a week-long national event.", amount: "Nearly $1M in prizes total", deadline: "Est. 2027 — Feb–Mar", deadlineStatus: "est", deadlineSort: "2027-02-15", eligibility: "Grades 7–12, must qualify through affiliated regional science fair, individual or team of 2", difficulty: "Competitive", international: false, link: "https://cwsf-espc.ca", stem: true, gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Multi-day event", compensated: true },
  { id: 13, name: "Skills Canada National Competition", category: "competitions", description: "The only national, Olympic-style, multi-trade and technology competition for young students and apprentices. Winners may represent Canada at WorldSkills.", amount: "Medals + Team Canada qualification", deadline: "Est. 2027 — Provincial qualifiers", deadlineStatus: "est", deadlineSort: "2027-04-01", eligibility: "Secondary/post-secondary in skilled trades/technology, max age 29", difficulty: "Competitive", international: false, link: "https://www.skillscompetencescanada.com", gradeLevels: ["Grades 11–12", "CEGEP", "University"], timeCommitment: "Multi-day event", compensated: true },
  { id: 14, name: "Canadian Computing Competition", category: "competitions", description: "Hosted by the University of Waterloo CEMC. A programming contest for secondary students. Top Senior participants are invited to the Canadian Computing Olympiad.", amount: "$500 gold / $200 silver + CCO invite", deadline: "Est. 2027 — Feb 2027", deadlineStatus: "est", deadlineSort: "2027-02-18", eligibility: "Canadian secondary students, born on/after July 1, 2006, Junior or Senior level", difficulty: "Moderate", international: false, link: "https://cemc.uwaterloo.ca/contests/computing.html", stem: true, gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: true },
  { id: 15, name: "DECA Ontario", category: "competitions", description: "Provincial business case competition covering marketing, finance, hospitality, and entrepreneurship. Top performers qualify for ICDC.", amount: "Medals + ICDC qualification", deadline: "Est. 2027 — Dec 2026 / Feb 2027", deadlineStatus: "est", deadlineSort: "2026-12-12", eligibility: "Ontario high school students grades 9–12, business categories, team or individual events", difficulty: "Competitive", international: false, link: "https://deca.ca", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Multi-day event", compensated: true },
  { id: 16, name: "SHAD Program", category: "internships", description: "Month-long STEM + entrepreneurship program at Canadian universities. Students live on campus and work on real-world design challenges.", amount: "Paid program (~$6,500 fee, bursaries)", deadline: "Est. 2026 — Nov 30", deadlineStatus: "est", deadlineSort: "2026-11-30", eligibility: "Canadian Grade 11–12 students, strong academics, demonstrated leadership and creativity", difficulty: "Competitive", international: false, link: "https://www.shad.ca", stem: true, gradeLevels: ["Grades 11–12"], timeCommitment: "4-week residential", compensated: true },
  { id: 17, name: "RIOT Program at SickKids", category: "internships", description: "Research internship at the Hospital for Sick Children, Toronto. Students work alongside world-class researchers in labs, gaining hands-on biomedical research experience.", amount: "Unpaid but prestigious", deadline: "Est. 2026 — Mar 15", deadlineStatus: "est", deadlineSort: "2026-03-15", eligibility: "Grade 11–12 students, strong interest in STEM/research, Toronto area preferred", difficulty: "Moderate", international: false, link: "https://www.sickkids.ca/en/research/", stem: true, gradeLevels: ["Grades 11–12"], timeCommitment: "Summer program", compensated: false },
  { id: 18, name: "RBC High School Internship", category: "internships", description: "Summer internship at RBC for high school students interested in finance and technology. Gain real-world experience in banking operations and digital innovation.", amount: "Paid internship", deadline: "Est. 2027 — Feb 28", deadlineStatus: "est", deadlineSort: "2027-02-28", eligibility: "Canadian Grade 11–12 students, interest in finance/tech, strong communication skills", difficulty: "Competitive", international: false, link: "https://jobs.rbc.com/ca/en/students", gradeLevels: ["Grades 11–12"], timeCommitment: "Summer program", compensated: true },
  { id: 19, name: "TD Bank Student Experience Program", category: "internships", description: "Rotational exposure program for high school students at TD Bank. Explore retail banking, wealth management, and corporate operations through structured rotations.", amount: "Paid program", deadline: "Est. 2027 — Mar 1", deadlineStatus: "est", deadlineSort: "2027-03-01", eligibility: "Canadian Grade 11–12 students, min 75% average, interest in business and finance", difficulty: "Moderate", international: false, link: "https://jobs.td.com/en-CA/students/", gradeLevels: ["Grades 11–12"], timeCommitment: "Summer program", compensated: true },
  { id: 20, name: "BMO High School Co-op", category: "internships", description: "Co-op placement in banking and financial services at BMO. Hands-on experience in customer service, financial analysis, and branch operations.", amount: "Paid co-op placement", deadline: "Est. 2027 — Apr 15", deadlineStatus: "est", deadlineSort: "2027-04-15", eligibility: "Canadian Grade 11–12 students enrolled in co-op education, interest in financial services", difficulty: "Moderate", international: false, link: "https://jobs.bmo.com/ca/en/students", gradeLevels: ["Grades 11–12"], timeCommitment: "Semester-long", compensated: true },
  { id: 21, name: "Telus Youth Internship", category: "internships", description: "Tech-focused paid summer internship at Telus. Work on real digital transformation projects in software development, data analytics, cybersecurity, and network engineering.", amount: "Paid internship", deadline: "Est. 2027 — Feb 15", deadlineStatus: "est", deadlineSort: "2027-02-15", eligibility: "Canadian Grade 11–12 students, interest in technology, coding experience preferred", difficulty: "Moderate", international: false, link: "https://www.telus.com/en/about/careers", stem: true, gradeLevels: ["Grades 11–12"], timeCommitment: "Summer program", compensated: true },
  { id: 22, name: "Waterloo Engineering Science Quest (ESQ)", category: "summer-programs", description: "Week-long on-campus STEM camp at the University of Waterloo. Hands-on labs, design challenges, and mentorship from Waterloo engineering students.", amount: "Paid program (~$450–$650/week)", deadline: "Est. 2026 — May 31", deadlineStatus: "est", deadlineSort: "2026-05-31", eligibility: "Canadian Grade 9–10 students, interest in STEM, no prior experience required", difficulty: "Easy", international: false, link: "https://uwaterloo.ca/engineering-science-quest", stem: true, gradeLevels: ["Grades 9–10"], timeCommitment: "1-week camp", compensated: true },
  { id: 23, name: "UBC Future Global Leaders", category: "summer-programs", description: "Leadership and global issues residential program at the University of British Columbia. Academic coursework, leadership workshops, and cultural excursions in Vancouver.", amount: "Paid program (~$5,500)", deadline: "Est. 2026 — Apr 30", deadlineStatus: "est", deadlineSort: "2026-04-30", eligibility: "Grade 10–12 students, strong academics, interest in global leadership and social issues", difficulty: "Moderate", international: false, link: "https://youth.ubc.ca/programs/future-global-leaders", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "2-week residential", compensated: true },
  { id: 24, name: "McMaster Engineering Experience", category: "summer-programs", description: "Hands-on engineering summer program at McMaster University. Design, build, and test engineering projects with faculty in state-of-the-art labs.", amount: "Paid program (~$800/week)", deadline: "Est. 2026 — May 15", deadlineStatus: "est", deadlineSort: "2026-05-15", eligibility: "Canadian Grade 11–12 students, interest in engineering, min 80% in math/science", difficulty: "Moderate", international: false, link: "https://www.eng.mcmaster.ca", stem: true, gradeLevels: ["Grades 11–12"], timeCommitment: "1-week camp", compensated: true },
  { id: 25, name: "Queen's University Leadership Program", category: "summer-programs", description: "Residential summer leadership academy at Queen's University. Workshops, team challenges, and community projects on the historic Kingston campus.", amount: "Paid program (~$4,500)", deadline: "Est. 2026 — Apr 1", deadlineStatus: "est", deadlineSort: "2026-04-01", eligibility: "Grade 10–12 students, demonstrated leadership potential, strong communication skills", difficulty: "Moderate", international: false, link: "https://www.queensu.ca", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "2-week residential", compensated: true },
  { id: 26, name: "Algonquin Summer Immersion", category: "summer-programs", description: "French immersion + STEM summer program combining language learning with hands-on projects in robotics, coding, and environmental science.", amount: "Paid program (~$1,200/week)", deadline: "Est. 2026 — May 1", deadlineStatus: "est", deadlineSort: "2026-05-01", eligibility: "Grade 9–12 students, any French level welcome, interest in STEM and language learning", difficulty: "Easy", international: false, link: "https://www.algonquincollege.com/international/go/summer-programs/", stem: true, gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "2-week program", compensated: true },
  { id: 27, name: "MIT Launch High School", category: "summer-programs", description: "Entrepreneurship summer program at MIT for high school students worldwide. Develop and launch real startups with MIT mentorship, ending in a pitch competition.", amount: "Paid program (~$9,500 USD)", deadline: "Est. 2026 — Jan 15", deadlineStatus: "est", deadlineSort: "2026-01-15", eligibility: "Grade 10–12 students globally, entrepreneurial mindset, strong academics, application + interview", difficulty: "Competitive", international: true, link: "https://www.launchx.com", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "4-week residential", compensated: true },
  { id: 28, name: "Stanford Pre-Collegiate", category: "summer-programs", description: "Academic enrichment summer program at Stanford University. Courses in humanities, sciences, arts, and business taught by Stanford instructors on campus.", amount: "Paid program (~$8,000 USD)", deadline: "Est. 2026 — Mar 1", deadlineStatus: "est", deadlineSort: "2026-03-01", eligibility: "Grade 9–12 students globally, strong academics, essays and recommendations required", difficulty: "Competitive", international: true, link: "https://spcs.stanford.edu/programs/stanford-pre-collegiate-summer-institutes", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "3-week residential", compensated: true },
  { id: 29, name: "Suncor Energy Foundation Youth Fund", category: "grants", description: "Up to $5,000 for student-led community or environmental projects in sustainability, education, or community well-being.", amount: "Up to $5,000", deadline: "Est. 2026 — Jun 30", deadlineStatus: "est", deadlineSort: "2026-06-30", eligibility: "Canadian Grade 9–12 students, youth-led project with community impact, adult mentor required", difficulty: "Moderate", international: false, link: "https://www.suncor.com/community", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Project-based", compensated: true },
  { id: 30, name: "Canada Service Corps Micro-grant", category: "grants", description: "Federal micro-grants for youth-led social projects, up to $1,500. Support community initiatives in environment, health, reconciliation, and inclusion.", amount: "Up to $1,500", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "Canadian youth 15–30, youth-led project, must partner with a community organization", difficulty: "Easy", international: false, link: "https://www.canada.ca/en/services/youth/canada-service-corps.html", gradeLevels: ["Grades 9–10", "Grades 11–12", "CEGEP"], timeCommitment: "Project-based", compensated: true },
  { id: 31, name: "Ontario Trillium Foundation Youth Grant", category: "grants", description: "Funding for youth community initiatives in Ontario, up to $10,000. Supports projects that build youth leadership and address social issues locally.", amount: "Up to $10,000", deadline: "Est. 2026 — Aug 15", deadlineStatus: "est", deadlineSort: "2026-08-15", eligibility: "Ontario youth-led groups, registered charity or non-profit partner, community benefit focus", difficulty: "Moderate", international: false, link: "https://otf.ca", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Project-based", compensated: true },
  { id: 32, name: "Duke of Edinburgh Canada Award Fund", category: "grants", description: "Small project grants tied to the Duke of Edinburgh award. Financial support for youth pursuing Bronze, Silver, or Gold who need help with expedition costs.", amount: "Up to $1,000", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "Canadian youth enrolled in Duke of Edinburgh program, demonstrated financial need", difficulty: "Easy", international: false, link: "https://www.dukeofed.org", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Award program", compensated: true },
  { id: 33, name: "Inspirit Foundation Youth Grant", category: "grants", description: "Grants for pluralism and inclusion projects by youth. Fund initiatives that bring diverse communities together and promote understanding across cultural differences.", amount: "Up to $5,000", deadline: "Est. 2026 — Jul 31", deadlineStatus: "est", deadlineSort: "2026-07-31", eligibility: "Canadian youth 15–30, project focused on pluralism/inclusion, non-profit or community partner", difficulty: "Moderate", international: false, link: "https://inspiritfoundation.org", gradeLevels: ["Grades 9–10", "Grades 11–12", "CEGEP"], timeCommitment: "Project-based", compensated: true },
  { id: 34, name: "Google.org Impact Challenge Youth", category: "grants", description: "Project funding for tech-for-good ideas from students internationally. Support technology solutions that address social, environmental, or economic challenges.", amount: "Up to $25,000", deadline: "Est. 2026 — Sep 30", deadlineStatus: "est", deadlineSort: "2026-09-30", eligibility: "Grade 11–12 students globally, tech-focused project with social impact, team-based application", difficulty: "Competitive", international: true, link: "https://impactchallenge.withgoogle.com", stem: true, gradeLevels: ["Grades 11–12"], timeCommitment: "Project-based", compensated: true },
  { id: 35, name: "CAIMUN", category: "competitions", description: "Canada International Model United Nations — Vancouver's premier MUN conference and one of the largest in Canada. Over 1,000 participants compete in two dozen unique committees at the Sheraton Vancouver Wall Centre.", amount: "Awards + Best Delegate recognition", deadline: "Est. 2027 — registration opens May 2026", deadlineStatus: "est", deadlineSort: "2027-02-01", eligibility: "High school students globally, all experience levels, overnight and day delegate options available", difficulty: "Competitive", international: true, link: "https://caimun.ca", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Multi-day conference", compensated: false, isNew: true },
  { id: 36, name: "CAHSMUN", category: "competitions", description: "Canadian High Schools Model United Nations — one of North America's largest MUN conferences, held annually in Vancouver. 22 committees covering diplomacy, security, and international policy.", amount: "Awards + Best Delegate recognition", deadline: "Est. 2027 — Apr 9–11", deadlineStatus: "est", deadlineSort: "2027-04-09", eligibility: "High school students, school delegation registration required, all experience levels welcome", difficulty: "Moderate", international: false, link: "https://cahsmun.org", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "3-day conference", compensated: false, isNew: true },
  { id: 37, name: "CAHSMUN Horizons", category: "competitions", description: "The training-focused sister conference of CAHSMUN, held in Richmond BC. Emphasizes delegate development and accessible MUN experience with smaller committees and intensive coaching.", amount: "Awards + Best Delegate recognition", deadline: "Est. 2026 — Dec 4–6", deadlineStatus: "est", deadlineSort: "2026-12-04", eligibility: "High school students in BC, beginner-friendly, school or independent registration", difficulty: "Easy", international: false, link: "https://horizons.cahsmun.org", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "3-day conference", compensated: false, isNew: true },
  { id: 38, name: "SPAMUN", category: "competitions", description: "Southpointe Academy Model United Nations — Metro Vancouver's beginner-friendly MUN day conference in Tsawwassen. Small committee sizes give staff more focus on every delegate.", amount: "Awards + Best Delegate recognition", deadline: "Est. 2027 — date TBA", deadlineStatus: "est", deadlineSort: "2027-03-01", eligibility: "High school students in Metro Vancouver, beginner-friendly, all experience levels", difficulty: "Easy", international: false, link: "https://cmun.ca/conferences", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: false, isNew: true },
  { id: 39, name: "Prosper Vancouver", category: "competitions", description: "Canada's premier youth business conference and case competition for high school students. Includes mentorship workshops, networking with business leaders, overnight stay at the Hyatt Regency Vancouver, and a $2,000 prize for top teams.", amount: "$2,000 top prize + Prosper Ivey Invitational qualification", deadline: "Est. 2027 — Apr 25–26", deadlineStatus: "est", deadlineSort: "2027-04-25", eligibility: "High school students across Canada, team-based application, no prior business experience required", difficulty: "Competitive", international: false, link: "https://www.prospervancouver.org", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "2-day conference", compensated: true, isNew: true },
  { id: 40, name: "STRIVE Competition", category: "competitions", description: "Tech-centric business case competition for high school students held at UBC Sauder School of Business. Founded in 2016 to provide a technology-focused business competition experience for students in the Lower Mainland and across Canada.", amount: "Cash prizes + recognition", deadline: "Est. 2027 — Feb 2027", deadlineStatus: "est", deadlineSort: "2027-02-21", eligibility: "High school students in BC and across Canada, interest in technology and business", difficulty: "Moderate", international: false, link: "https://www.strivecompetition.org", stem: true, gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "2-day competition", compensated: true, isNew: true },
  { id: 41, name: "Enhance Vancouver", category: "competitions", description: "Vancouver's premier student-led business case competition held at UBC Sauder. Founded by Vancouver high school students to transform the high school business landscape through innovative experiences.", amount: "Cash prizes + recognition", deadline: "Est. 2027 — Apr 2027", deadlineStatus: "est", deadlineSort: "2027-04-04", eligibility: "High school students in BC, team-based, all experience levels welcome", difficulty: "Moderate", international: false, link: "https://www.enhancevancouver.org", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: true, isNew: true },
  { id: 42, name: "Ascend Competition", category: "competitions", description: "Lower Mainland's first case competition with two difficulty streams — Novice and Advanced. Strong emphasis on learning and feedback sessions after the conference. Top teams qualify for the Prosper Ivey Invitational.", amount: "$500 Novice / $750 Advanced + Ivey Invitational qualification", deadline: "Est. 2026 — Nov 2026", deadlineStatus: "est", deadlineSort: "2026-11-15", eligibility: "High school students in BC, two streams for different experience levels, team-based", difficulty: "Easy", international: false, link: "https://www.ascendcompetition.org", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: true, isNew: true },
  { id: 43, name: "Envision Case Competition", category: "competitions", description: "Student-led business case competition in Vancouver empowering high school students through innovation, teamwork, and real-world business challenges.", amount: "Cash prizes + recognition", deadline: "Est. 2027 — date TBA", deadlineStatus: "est", deadlineSort: "2027-03-01", eligibility: "High school students in BC, team-based, all experience levels", difficulty: "Moderate", international: false, link: "https://www.envisioncasecompetition.com", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: true, isNew: true },
  { id: 44, name: "Ivey High School Case Competition — Vancouver", category: "competitions", description: "Hosted by Ivey Business School at Western University. Students collaborate in teams to solve real-world business cases and present to a panel of judges. Vancouver edition held at Mulgrave School.", amount: "Recognition + Ivey Business School exposure", deadline: "Est. 2027 — Apr 2027", deadlineStatus: "est", deadlineSort: "2027-04-18", eligibility: "Grades 10–12 students, no prior business experience needed, team-based with students from different schools", difficulty: "Easy", international: false, link: "https://www.ivey.uwo.ca/high-school-case-competitions", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Single day", compensated: false, isNew: true },
  { id: 45, name: "LegalEagleBee Policy Video Competition", category: "competitions", description: "Online competition for high school and college students interested in law and political science. Create a short policy video on a legal or political topic of your choice. Helps build a pre-law portfolio for college applications.", amount: "Recognition + certificate", deadline: "Rolling monthly", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "High school and college students globally, interest in law or political science, online submission", difficulty: "Easy", international: true, link: "https://www.legaleaglebee.com/policy-video-competition", gradeLevels: ["Grades 9–10", "Grades 11–12", "CEGEP"], timeCommitment: "Flexible schedule", compensated: false, isNew: true },
  { id: 46, name: "LegalEagleBee Judicial Case Competition", category: "competitions", description: "Online judicial case competition for high school students interested in law. Argue both sides of a legal case before a panel of judges. Builds advocacy and analytical skills for pre-law students.", amount: "Recognition + certificate", deadline: "Rolling", deadlineStatus: "open", deadlineSort: "2099-12-31", eligibility: "High school students globally, interest in law, online format", difficulty: "Moderate", international: true, link: "https://www.legaleaglebee.com", gradeLevels: ["Grades 9–10", "Grades 11–12", "CEGEP"], timeCommitment: "Flexible schedule", compensated: false, isNew: true },
  { id: 47, name: "John Locke Institute Essay Competition", category: "competitions", description: "Prestigious international essay competition open to students under 19. Submit essays across categories including Philosophy, Politics, Economics, History, Psychology, and Law. Shortlisted students invited to Oxford for an awards conference.", amount: "Prize + invitation to Oxford awards conference", deadline: "May 31, 2027", deadlineStatus: "est", deadlineSort: "2027-05-31", eligibility: "Students under 19 globally, one essay per category, any nationality", difficulty: "Competitive", international: true, link: "https://www.johnlockeinstitute.com/essay-competition", gradeLevels: ["Grades 9–10", "Grades 11–12", "CEGEP"], timeCommitment: "Application only", compensated: true, isNew: true },
  { id: 48, name: "Fraser Institute Student Essay Contest", category: "competitions", description: "Annual Canadian essay contest on economics and public policy open to high school and post-secondary students. Winning essays are peer-reviewed and published. Cash prizes for top five submissions.", amount: "Cash prizes for top 5 submissions", deadline: "Est. 2026 — deadline TBA", deadlineStatus: "est", deadlineSort: "2026-10-01", eligibility: "Students attending school in Canada 2025/2026 or enrolled in 2026/2027, international students studying in Canada eligible, 1,000–1,500 words", difficulty: "Moderate", international: false, link: "https://www.fraserinstitute.org/education-programs/student-essay-contest", gradeLevels: ["Grades 11–12", "CEGEP"], timeCommitment: "Application only", compensated: true, isNew: true },
  { id: 49, name: "Horizon Academic Essay Prize", category: "competitions", description: "Selective international essay competition for high school students evaluated by faculty from Yale, Harvard, Oxford, and Cambridge. Theme for 2026 edition: 'The Pursuit of Progress'. Top entries win cash prizes and full scholarships to Horizon's academic programs.", amount: "Up to full scholarship to Horizon programs + cash prizes", deadline: "Est. 2027 — Feb 1", deadlineStatus: "est", deadlineSort: "2027-02-01", eligibility: "High school students from any country, enrolled in high school as of September 1 2026, any subject area", difficulty: "Competitive", international: true, link: "https://www.horizonacademic.com/essay-prize", gradeLevels: ["Grades 9–10", "Grades 11–12"], timeCommitment: "Application only", compensated: true, isNew: true },
];

export const categories = [
  { id: "scholarships", name: "Scholarships" },
  { id: "volunteering", name: "Volunteering" },
  { id: "competitions", name: "Competitions" },
  { id: "internships", name: "Internships & Co-op" },
  { id: "summer-programs", name: "Summer Programs" },
  { id: "grants", name: "Grants & Funding" },
];
