/**
 * BCI partner organizations.
 *
 * Typed data module built from partners.json. Edit entries here to update the
 * Partners section — components import from this module rather than hardcoding.
 * Some social handle fields may be empty strings; render code omits those icons.
 */
export interface Partner {
  name: string;
  location: string;
  region: "BC/Canada" | "International";
  theme: string;
  description: string;
  opportunity: string;
  opportunityType: string;
  instagram?: string;
  tiktok?: string;
  website?: string;
  linkedin?: string;
  facebook?: string;
}

export const partners: Partner[] = [
  { name: "The Two Lens Journal", location: "Vancouver, BC", region: "BC/Canada", theme: "Writing & Journalism", description: "A Vancouver-based student publication that breaks down complex issues in politics, economics, and policy through its signature dual-lens format — pairing global, historical context with local impact and solutions. It gives young writers a place to publish rigorous, accessible analysis on the topics they care about.", opportunity: "Student Writer positions", opportunityType: "Writing", instagram: "@twolensjournal", tiktok: "@twolensjournal", website: "" },
  { name: "Loose Leaf Project", location: "Surrey, BC", region: "BC/Canada", theme: "Social Advocacy", description: "A student-led, community-focused initiative shining a light on overlooked social issues — from period poverty and youth food insecurity to senior isolation, housing insecurity, and support for domestic-violence survivors. Through awareness campaigns and community events, they amplify unheard voices.", opportunity: "Event volunteering, including the Women Empowerment Fair", opportunityType: "Volunteering", instagram: "@loose_leaf_project", tiktok: "", website: "" },
  { name: "NextGen Med", location: "Langley, BC", region: "BC/Canada", theme: "Medicine & Healthcare", description: "Helps students explore and prepare for careers in medicine through internships, research, and hands-on learning across healthcare fields — giving aspiring medical professionals valuable experience for college applications.", opportunity: "Medical Careers Exploration Internship and Marketing Internship", opportunityType: "Internship", instagram: "@nextgen_med.21", tiktok: "@nextgen.med", website: "", linkedin: "NextGen Med" },
  { name: "Open Minds Foundation", location: "Vancouver, BC", region: "BC/Canada", theme: "Youth Leadership", description: "A student-led nonprofit dedicated to empowering youth leadership and student-led initiatives. In partnership with BCI on the Open Academy Project, they help equip the next generation with STEM, business, and leadership skills.", opportunity: "Leadership roles and volunteering", opportunityType: "Leadership", instagram: "@openmindsfnd", tiktok: "", website: "" },
  { name: "BC Junior Math Association", location: "British Columbia", region: "BC/Canada", theme: "STEM & Education", description: "A student-led organization making math fun and accessible for elementary learners through high-school mentorship. They run competition-based weekly lessons across 7+ schools, host math competitions, and are launching a math league for high schoolers.", opportunity: "Volunteer mentors to teach math at elementary schools", opportunityType: "Volunteering", instagram: "@bcjuniormath", tiktok: "", website: "" },
  { name: "British Columbia Youth Council", location: "Vancouver, BC", region: "BC/Canada", theme: "Civic & Policy", description: "A youth-led, youth-serving organization amplifying young people's voices and connecting youth-led initiatives across the province. Through policy publications, regional youth councils, and dialogue with elected officials, they turn youth activism into real influence.", opportunity: "Leadership positions", opportunityType: "Leadership", instagram: "@bcyouthcouncil.org", tiktok: "", website: "bcyouthcouncil.org" },
  { name: "Pediatric Picnic", location: "Alberta, Canada", region: "BC/Canada", theme: "Medicine & Healthcare", description: "A youth-led community for students aspiring to careers in medicine and pediatrics. They connect future healthcare professionals and guide them through their journey with mentorship, resources, and support.", opportunity: "Mentorship for students pursuing medicine", opportunityType: "Mentorship", instagram: "@pediatric.picnic", tiktok: "", website: "" },
  { name: "Global Voices", location: "Chicago, USA", region: "International", theme: "Debate & Public Speaking", description: "A student-led initiative making debate and public-speaking education free and accessible. Through interactive online classes for students in grades 1–8, they build communication, advocacy, and critical-thinking skills from an early age.", opportunity: "Free beginner and intermediate debate/public-speaking classes", opportunityType: "Program", instagram: "@Globalvoices.team", tiktok: "GlobalVoices_Team", website: "", facebook: "GlobalVoicesTeam" },
  { name: "Marketed", location: "Varanasi, India", region: "International", theme: "Culture & Media", description: "A youth-led cultural publication and archive exploring how branding, fashion, media, technology, and internet culture shape identity. Through thoughtful, visually driven analysis, they document contemporary cultural moments for future generations.", opportunity: "Content Writer, Social Media, and Graphic Designer volunteer roles", opportunityType: "Volunteering", instagram: "@marketedzine", tiktok: "", website: "" },
  { name: "Mental Health Initiative", location: "Saudi Arabia", region: "International", theme: "Mental Health", description: "A youth-led organization dedicated to raising mental-health awareness, reducing stigma, and making well-being resources accessible. Through education, content, and community campaigns, they help young people better understand and care for their mental health.", opportunity: "Leadership and volunteer roles (social media, writing, events)", opportunityType: "Leadership", instagram: "@mhi.organization", tiktok: "", website: "" },
  { name: "Mindful Arts Initiative", location: "Brooklyn, NY, USA", region: "International", theme: "Arts & Wellness", description: "A nonprofit bringing wellness to young children through creativity. Their art-based activities help students develop mindfulness through expression, giving kids a healthy outlet while nurturing emotional well-being.", opportunity: "Volunteer and collaborative roles designing student activities", opportunityType: "Volunteering", instagram: "@mindfulartsinitiative", tiktok: "", website: "" },
  { name: "Nourish Nutrition Project", location: "Madison, USA", region: "International", theme: "Health & Nutrition", description: "A youth-led nonprofit making nutrition education accessible, engaging, and empowering for underserved communities. Through workshops, outreach, and service projects, their volunteers promote healthy, sustainable habits and work to close nutrition gaps.", opportunity: "Volunteer roles and Chapter Lead positions", opportunityType: "Volunteering", instagram: "@nourishnutritionproject", tiktok: "", website: "" },
  { name: "Global Future Leaders", location: "International", region: "International", theme: "Youth Leadership", description: "A youth-led nonprofit inspiring and equipping young people to become tomorrow's leaders. Through research, content creation, and community outreach — much of it focused on global healthcare issues — members make a real impact while building leadership skills.", opportunity: "Volunteer roles across research, content, and outreach", opportunityType: "Volunteering", instagram: "@globalfutureleaders_", tiktok: "globalfutureleaders", website: "", linkedin: "The Global Future Leaders" },
  { name: "Innovatory Medical Youth Elite Society", location: "International", region: "International", theme: "Medicine & First Aid", description: "A youth-led organization on a mission to make CPR and life-saving skills essential in every community. They train and certify young people to help deliver high-quality first-aid and CPR instruction.", opportunity: "Youth Instructor Assistant roles (certification supported)", opportunityType: "Volunteering", instagram: "@imyescpr", tiktok: "", website: "" },
  { name: "Project SugarWise", location: "International", region: "International", theme: "Health Awareness", description: "A student-led initiative making diabetes education more accessible and offering compassionate support to people living with diabetes, with a focus on understanding, encouragement, and mental-health support.", opportunity: "Graphic Designer and Fundraising volunteer roles", opportunityType: "Volunteering", instagram: "@sugarwise._", tiktok: "", website: "" },
  { name: "Caffeinated Commerce", location: "India", region: "International", theme: "Business & Marketing", description: "An emerging student-led marketing and business platform that simplifies commerce — from marketing strategy and brand breakdowns to economics — through research-based articles. A learning hub for students curious about the business world.", opportunity: "Learning opportunities in business, marketing, and economics", opportunityType: "Program", instagram: "@caffeinatedcommerce", tiktok: "", website: "thecaffeinatedcomm.wixsite.com/alisha" },
  { name: "STEMpathy", location: "Jakarta, Indonesia", region: "International", theme: "STEM & Social Impact", description: "A youth-led organization making STEM more accessible, engaging, and meaningful for students, with a mission to bridge STEM and social impact. Through content, outreach, and community events, they inspire curiosity and empower the next generation of innovators.", opportunity: "Leadership and volunteer roles across PR, events, media, writing, and design", opportunityType: "Leadership", instagram: "@stempathy.id", tiktok: "", website: "" },
  { name: "ArtRx", location: "USA", region: "International", theme: "Arts & Healthcare", description: "Makes healthcare less intimidating and more understandable for children through art, anatomy education, and interactive outreach — improving pediatric health literacy and creating child-friendly resources for medical settings.", opportunity: "Volunteer roles creating anatomy workshops and magazine artwork", opportunityType: "Volunteering", instagram: "@artrx.project", tiktok: "", website: "" },
  { name: "TopTierTeam", location: "Shymkent, Kazakhstan", region: "International", theme: "Events & Community", description: "A student-led organization that builds community through large-scale events — from essay awards to olympiads — bringing together diverse participants across their city and beyond, and seeking to build bridges with students worldwide.", opportunity: "Leadership, volunteering, and event participation (essay awards, olympiads)", opportunityType: "Leadership", instagram: "", tiktok: "", website: "" },
];
