/**
 * Student profiles — "what did admitted students actually do, and where did it get them?"
 *
 * ── PLACEHOLDER DATA ──
 * Every entry below is fictional and must be replaced with real, consented student
 * interviews before launch. `relatedOpportunityIds` point at real entries in
 * src/lib/opportunities.ts so cross-links work today.
 *
 * The larger seed batch exists purely so the "Find your match" quiz has coverage
 * across every field/major, school, and theme a user can pick — demo data only,
 * invented names, remove before publishing real profiles.
 */

export type ThemeId = "stem" | "leadership" | "service" | "arts" | "athletics" | "entrepreneurship";

export const themeLabels: Record<ThemeId, string> = {
  stem: "STEM & Research",
  leadership: "Leadership",
  service: "Community Service",
  arts: "Arts & Culture",
  athletics: "Athletics",
  entrepreneurship: "Entrepreneurship",
};

export interface Extracurricular {
  role: string;
  org: string;
  theme: ThemeId;
  description: string;
  relatedOpportunityIds?: number[]; // Opportunity.id from src/lib/opportunities.ts
}

export interface Profile {
  id: string; // URL slug for /profiles/$id
  name: string;
  major: string;
  gradYear: number;
  location: string;
  curriculum: string;
  stats: { label: string; value: string }[]; // self-reported
  themes: ThemeId[];
  extracurriculars: Extracurricular[]; // ordered — the first two drive the card roles line
  awards: string[];
  acceptedSchoolIds: string[]; // School.id[]; includes attendingSchoolId by convention
  attendingSchoolId: string;
  sourceVideoUrl: string;
  verified?: boolean;
  consent: boolean; // HARD GATE — non-consenting profiles never render anywhere
}

const allProfiles: Profile[] = [
  {
    id: "maya-thompson",
    name: "Maya Thompson",
    major: "Computer Science",
    gradYear: 2025,
    location: "Richmond, BC",
    curriculum: "BC Dogwood + 6 AP",
    stats: [
      { label: "Average", value: "96%" },
      { label: "SAT", value: "1520" },
    ],
    themes: ["stem", "leadership"],
    extracurriculars: [
      {
        role: "Co-President",
        org: "Coding Club",
        theme: "stem",
        description:
          "Grew the club from 12 to 60 members, ran weekly contest-prep sessions, and coached two junior teams through the Canadian Computing Competition.",
        relatedOpportunityIds: [14],
      },
      {
        role: "Head Delegate",
        org: "CAHSMUN",
        theme: "leadership",
        description:
          "Led the school's 14-person Model UN delegation for two years; best delegate in a 120-person General Assembly committee.",
        relatedOpportunityIds: [36],
      },
      {
        role: "Founder",
        org: "Girls Who Code Richmond",
        theme: "service",
        description:
          "Started a free weekend intro-to-Python program for middle-school girls, taught by senior CS students.",
      },
    ],
    awards: ["CCC Senior Distinction (2024)", "Schulich Leader Nominee (2025)"],
    acceptedSchoolIds: ["waterloo", "ubc", "sfu", "stanford", "uoft", "mcgill"],
    attendingSchoolId: "waterloo",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "arjun-patel",
    name: "Arjun Patel",
    major: "Life Sciences",
    gradYear: 2024,
    location: "Surrey, BC",
    curriculum: "IB Diploma",
    stats: [{ label: "IB", value: "42/45" }],
    themes: ["stem", "service"],
    extracurriculars: [
      {
        role: "Research Intern",
        org: "RIOT Program at SickKids",
        theme: "stem",
        description:
          "Summer research placement in a pediatric oncology lab — cell-culture work and a poster presentation at the end-of-program symposium.",
        relatedOpportunityIds: [17],
      },
      {
        role: "Volunteer Lead",
        org: "BC Children's Hospital",
        theme: "service",
        description:
          "300+ hours across two years in the youth volunteer program; trained new volunteers on the family-support desk.",
        relatedOpportunityIds: [57],
      },
    ],
    awards: ["IB Biology Subject Award (2024)"],
    acceptedSchoolIds: ["ubc", "uoft", "mcgill"],
    attendingSchoolId: "uoft",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "emilie-tremblay",
    name: "Émilie Tremblay",
    major: "Political Science",
    gradYear: 2025,
    location: "Montréal, QC",
    curriculum: "CEGEP DEC — Social Science",
    stats: [{ label: "R-score", value: "34.2" }],
    themes: ["leadership", "arts"],
    extracurriculars: [
      {
        role: "Editor-in-Chief",
        org: "Le Journal Étudiant",
        theme: "arts",
        description:
          "Ran a bilingual student paper with a 15-person masthead; launched a monthly long-form interview series with local politicians.",
      },
      {
        role: "Captain",
        org: "Debate Team",
        theme: "leadership",
        description:
          "Captained the team to a provincial final; organized a 200-student regional tournament.",
        relatedOpportunityIds: [1, 3],
      },
    ],
    awards: ["Loran Award Semifinalist (2025)", "Forces AVENIR Nominee (2024)"],
    acceptedSchoolIds: ["mcgill", "uoft", "harvard"],
    attendingSchoolId: "mcgill",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "daniel-okafor",
    name: "Daniel Okafor",
    major: "Computer Science",
    gradYear: 2024,
    location: "Burnaby, BC",
    curriculum: "BC Dogwood + 5 AP",
    stats: [{ label: "Average", value: "94%" }],
    themes: ["stem", "entrepreneurship"],
    extracurriculars: [
      {
        role: "Co-Founder",
        org: "TutorLink",
        theme: "entrepreneurship",
        description:
          "Built a peer-tutoring booking site used by three local schools; handled the product side.",
        relatedOpportunityIds: [242],
      },
      {
        role: "Contest Programmer",
        org: "CS Club",
        theme: "stem",
        description:
          "Weekly competitive-programming practice; qualified for USACO Silver division.",
        relatedOpportunityIds: [105, 14],
      },
      {
        role: "Hackathon Regular",
        org: "JAMHacks",
        theme: "stem",
        description:
          "Shipped a transit-delay tracker in 24 hours with two teammates; finalist project.",
        relatedOpportunityIds: [236],
      },
    ],
    awards: ["USACO Silver (2023)", "JAMHacks Finalist (2023)"],
    acceptedSchoolIds: ["ubc", "sfu", "ualberta"],
    attendingSchoolId: "ubc",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    major: "Economics",
    gradYear: 2025,
    location: "Coquitlam, BC",
    curriculum: "IB Diploma",
    stats: [{ label: "IB", value: "41/45" }],
    themes: ["leadership", "entrepreneurship"],
    extracurriculars: [
      {
        role: "President",
        org: "Investment Club",
        theme: "entrepreneurship",
        description:
          "Ran a mock-portfolio league for 40 students and a speaker series with local advisors.",
        relatedOpportunityIds: [116],
      },
      {
        role: "Delegate",
        org: "CAIMUN",
        theme: "leadership",
        description: "Two conference cycles in economic committees; honourable mention in ECOSOC.",
        relatedOpportunityIds: [35],
      },
      {
        role: "Columnist",
        org: "School Paper",
        theme: "arts",
        description: "Monthly plain-language column explaining one economics idea from the news.",
      },
    ],
    awards: ["International Economics Olympiad — National Round Qualifier (2024)"],
    acceptedSchoolIds: ["uoft", "ubc", "queens"],
    attendingSchoolId: "uoft",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "lucas-mendes",
    name: "Lucas Mendes",
    major: "Economics",
    gradYear: 2023,
    location: "Winnipeg, MB",
    curriculum: "MB Diploma + 3 AP",
    stats: [{ label: "Average", value: "92%" }],
    themes: ["service", "leadership"],
    extracurriculars: [
      {
        role: "Treasurer",
        org: "Student Council",
        theme: "leadership",
        description: "Managed a $12k activities budget and published it openly each term.",
      },
      {
        role: "Volunteer Assistant",
        org: "Community Tax Clinic",
        theme: "service",
        description: "Helped newcomers file simple returns during two tax seasons.",
      },
      {
        role: "Case Competitor",
        org: "DECA",
        theme: "entrepreneurship",
        description: "Provincial-level finance case competitor.",
        relatedOpportunityIds: [172],
      },
    ],
    awards: [],
    acceptedSchoolIds: ["queens", "western", "uoft"],
    attendingSchoolId: "western",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "fatima-al-rashid",
    name: "Fatima Al-Rashid",
    major: "Engineering",
    gradYear: 2025,
    location: "Surrey, BC",
    curriculum: "BC Dogwood + 4 AP",
    stats: [{ label: "Average", value: "95%" }],
    themes: ["stem", "leadership"],
    extracurriculars: [
      {
        role: "Team Captain",
        org: "FIRST Robotics 4571",
        theme: "stem",
        description:
          "Led a 25-student build team to a regional finalist finish; owned the drivetrain design.",
        relatedOpportunityIds: [71, 215],
      },
      {
        role: "Founder",
        org: "Girls in Engineering Night",
        theme: "leadership",
        description:
          "Quarterly hands-on build evenings for grade 8–9 girls, hosted at the school shop.",
      },
      {
        role: "Math Mentor",
        org: "Contest Prep Circle",
        theme: "service",
        description: "Coached juniors through Euclid past papers every Thursday lunch.",
        relatedOpportunityIds: [65],
      },
    ],
    awards: ["FIRST Regional Finalist (2024)", "Schulich Leader Nominee (2025)"],
    acceptedSchoolIds: ["waterloo", "ubc", "mcmaster"],
    attendingSchoolId: "waterloo",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "ethan-kowalski",
    name: "Ethan Kowalski",
    major: "Engineering",
    gradYear: 2024,
    location: "Kelowna, BC",
    curriculum: "BC Dogwood",
    stats: [{ label: "Average", value: "90%" }],
    themes: ["stem", "athletics"],
    extracurriculars: [
      {
        role: "Builder",
        org: "VEX Robotics Team",
        theme: "stem",
        description: "Two seasons on the build crew; provincial qualifier both years.",
        relatedOpportunityIds: [120],
      },
      {
        role: "Varsity Rower",
        org: "Rowing Club",
        theme: "athletics",
        description: "Coxed four; trained five mornings a week through the school year.",
      },
      {
        role: "Volunteer",
        org: "Repair Café",
        theme: "service",
        description: "Fixed small appliances and bikes at monthly community repair events.",
      },
    ],
    awards: [],
    acceptedSchoolIds: ["uvic", "ualberta", "sfu"],
    attendingSchoolId: "uvic",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "grace-liu",
    name: "Grace Liu",
    major: "Mathematics",
    gradYear: 2025,
    location: "Richmond, BC",
    curriculum: "BC Dogwood + 6 AP",
    stats: [
      { label: "Average", value: "98%" },
      { label: "SAT", value: "1560" },
    ],
    themes: ["stem"],
    extracurriculars: [
      {
        role: "Contest Lead",
        org: "Math Circle",
        theme: "stem",
        description:
          "Organized weekly problem sessions and school-wide writing of the Euclid and Beaver contests.",
        relatedOpportunityIds: [65, 66],
      },
      {
        role: "Problem Writer",
        org: "School Math Contest",
        theme: "stem",
        description: "Authored an annual 10-problem junior contest sat by 120 students.",
      },
      {
        role: "Grader & Mentor",
        org: "Junior Math League",
        theme: "service",
        description: "Marked contests and ran solution walkthroughs for grade 8 students.",
      },
    ],
    awards: [
      "Euclid Top 1% (2024)",
      "Canadian Open Math Challenge — Provincial Honour Roll (2024)",
    ],
    acceptedSchoolIds: ["waterloo", "uoft", "mit"],
    attendingSchoolId: "mit",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "omar-haddad",
    name: "Omar Haddad",
    major: "Mathematics",
    gradYear: 2023,
    location: "Ottawa, ON",
    curriculum: "OSSD + 4 AP",
    stats: [{ label: "Average", value: "96%" }],
    themes: ["stem", "service"],
    extracurriculars: [
      {
        role: "Founder",
        org: "Weekend Math Enrichment",
        theme: "service",
        description:
          "Free Saturday classes for middle-schoolers, grown to three volunteer instructors.",
      },
      {
        role: "Competitor",
        org: "CEMC Contests",
        theme: "stem",
        description: "Wrote Euclid and CSMC every year since grade 9; school champion twice.",
        relatedOpportunityIds: [65],
      },
    ],
    awards: ["Euclid School Champion (2022, 2023)"],
    acceptedSchoolIds: ["uoft", "mcgill", "queens"],
    attendingSchoolId: "mcgill",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "madison-clarke",
    name: "Madison Clarke",
    major: "Business",
    gradYear: 2024,
    location: "North Vancouver, BC",
    curriculum: "BC Dogwood",
    stats: [{ label: "Average", value: "91%" }],
    themes: ["entrepreneurship", "leadership"],
    extracurriculars: [
      {
        role: "Provincial Competitor",
        org: "DECA BC",
        theme: "entrepreneurship",
        description:
          "Marketing-event finalist at provincials; attended internationals as an observer.",
        relatedOpportunityIds: [172],
      },
      {
        role: "Founder",
        org: "Thrift Pop-Up",
        theme: "entrepreneurship",
        description:
          "Ran term-end second-hand clothing sales, donating proceeds to the local food bank.",
        relatedOpportunityIds: [242],
      },
      {
        role: "VP Events",
        org: "Student Council",
        theme: "leadership",
        description: "Planned spirit weeks and the year-end showcase for a 1,400-student school.",
      },
    ],
    awards: ["DECA BC Provincial Finalist (2024)"],
    acceptedSchoolIds: ["sfu", "ubc", "western"],
    attendingSchoolId: "sfu",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "jayden-cho",
    name: "Jayden Cho",
    major: "Business",
    gradYear: 2025,
    location: "Toronto, ON",
    curriculum: "OSSD + 4 AP",
    stats: [{ label: "Average", value: "93%" }],
    themes: ["entrepreneurship", "athletics"],
    extracurriculars: [
      {
        role: "Co-Founder",
        org: "Sneaker Restoration Service",
        theme: "entrepreneurship",
        description:
          "Cleaned and resold donated sneakers; reinvested profit into supplies and a small ad budget.",
        relatedOpportunityIds: [242],
      },
      {
        role: "Captain",
        org: "Basketball Team",
        theme: "athletics",
        description: "Senior team captain; organized off-season open gyms.",
      },
      {
        role: "Summer Associate",
        org: "Bank Youth Program",
        theme: "leadership",
        description: "Eight-week rotation through branch operations and community outreach.",
        relatedOpportunityIds: [19],
      },
    ],
    awards: [],
    acceptedSchoolIds: ["queens", "western", "uoft"],
    attendingSchoolId: "queens",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "sofia-petrov",
    name: "Sofia Petrov",
    major: "Linguistics",
    gradYear: 2025,
    location: "Victoria, BC",
    curriculum: "IB Diploma",
    stats: [{ label: "IB", value: "40/45" }],
    themes: ["arts", "service"],
    extracurriculars: [
      {
        role: "Editor",
        org: "Multilingual Zine",
        theme: "arts",
        description: "Published student writing in five languages with side-by-side translations.",
        relatedOpportunityIds: [174],
      },
      {
        role: "Conversation Buddy",
        org: "Newcomer Centre",
        theme: "service",
        description: "Weekly English practice sessions with newly arrived students.",
      },
      {
        role: "Reciter",
        org: "Poetry In Voice",
        theme: "arts",
        description: "School finalist two years running.",
        relatedOpportunityIds: [74],
      },
    ],
    awards: ["Poetry In Voice School Finalist (2024)"],
    acceptedSchoolIds: ["uvic", "ubc", "mcgill"],
    attendingSchoolId: "mcgill",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "noah-tanaka",
    name: "Noah Tanaka",
    major: "Linguistics",
    gradYear: 2023,
    location: "Vancouver, BC",
    curriculum: "BC Dogwood + 3 AP",
    stats: [{ label: "Average", value: "92%" }],
    themes: ["arts", "stem"],
    extracurriculars: [
      {
        role: "Creator",
        org: "Conlang YouTube Series",
        theme: "arts",
        description: "Built a constructed language on camera across 20 episodes; 8k subscribers.",
      },
      {
        role: "Volunteer Research Assistant",
        org: "University Phonetics Lab",
        theme: "stem",
        description:
          "Segmented and labelled audio recordings for a vowel study one afternoon a week.",
      },
      {
        role: "Essayist",
        org: "John Locke Institute Competition",
        theme: "arts",
        description: "Shortlisted in the junior category with an essay on language and thought.",
        relatedOpportunityIds: [47],
      },
    ],
    awards: ["John Locke Institute — Junior Shortlist (2022)"],
    acceptedSchoolIds: ["ubc", "uoft"],
    attendingSchoolId: "ubc",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "amara-osei",
    name: "Amara Osei",
    major: "Environmental Science",
    gradYear: 2024,
    location: "Nanaimo, BC",
    curriculum: "BC Dogwood",
    stats: [{ label: "Average", value: "89%" }],
    themes: ["service", "leadership"],
    extracurriculars: [
      {
        role: "Founder",
        org: "Shoreline Cleanup Crew",
        theme: "service",
        description:
          "Monthly beach cleanups with logged debris data submitted to a national database.",
        relatedOpportunityIds: [226, 95],
      },
      {
        role: "Youth Delegate",
        org: "Regional Climate Summit",
        theme: "leadership",
        description: "Presented the cleanup dataset to municipal staff and sat on the youth panel.",
      },
      {
        role: "Tree Planter",
        org: "TD Tree Days",
        theme: "service",
        description: "Three seasons of community planting events.",
        relatedOpportunityIds: [265],
      },
    ],
    awards: ["EcoAction Community Grant Recipient (2023)"],
    acceptedSchoolIds: ["uvic", "ubc"],
    attendingSchoolId: "uvic",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "henrik-larsen",
    name: "Henrik Larsen",
    major: "Environmental Science",
    gradYear: 2025,
    location: "Calgary, AB",
    curriculum: "AB Diploma",
    stats: [{ label: "Average", value: "90%" }],
    themes: ["stem", "service"],
    extracurriculars: [
      {
        role: "Citizen-Science Lead",
        org: "Christmas Bird Count",
        theme: "stem",
        description: "Coordinated the school's count route and submitted three years of data.",
      },
      {
        role: "Science Fair Competitor",
        org: "Canada-Wide Science Fair",
        theme: "stem",
        description: "Regional gold for a storm-drain water-quality testing project.",
        relatedOpportunityIds: [12],
      },
      {
        role: "Trail Volunteer",
        org: "Parks Stewardship Crew",
        theme: "service",
        description: "Summer weekends maintaining trails and removing invasive plants.",
      },
    ],
    awards: ["Regional Science Fair Gold (2024)"],
    acceptedSchoolIds: ["ualberta", "ubc"],
    attendingSchoolId: "ualberta",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "aisha-rahman",
    name: "Aisha Rahman",
    major: "Pre-Med",
    gradYear: 2025,
    location: "Surrey, BC",
    curriculum: "IB Diploma",
    stats: [{ label: "IB", value: "43/45" }],
    themes: ["stem", "service"],
    extracurriculars: [
      {
        role: "Youth Volunteer",
        org: "BC Children's Hospital",
        theme: "service",
        description: "200+ hours on the family-resource desk across two years.",
        relatedOpportunityIds: [57],
      },
      {
        role: "HOSA Competitor",
        org: "Health Sciences Club",
        theme: "stem",
        description: "Provincial medalist in medical terminology; club vice-president.",
        relatedOpportunityIds: [243],
      },
      {
        role: "Summer Research Student",
        org: "BC Children's Hospital Research Institute",
        theme: "stem",
        description: "High-school program placement in a childhood-asthma study.",
        relatedOpportunityIds: [198],
      },
    ],
    awards: ["HOSA BC Provincial Medalist (2024)"],
    acceptedSchoolIds: ["ubc", "mcmaster", "uoft"],
    attendingSchoolId: "mcmaster",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "marcus-boucher",
    name: "Marcus Boucher",
    major: "Pre-Med",
    gradYear: 2023,
    location: "Halifax, NS",
    curriculum: "NS Diploma + 2 AP",
    stats: [{ label: "Average", value: "94%" }],
    themes: ["service", "athletics"],
    extracurriculars: [
      {
        role: "First Aid Volunteer",
        org: "St. John Ambulance",
        theme: "service",
        description: "Event first-aid coverage and monthly training since grade 10.",
      },
      {
        role: "Lifeguard & Swim Instructor",
        org: "Community Pool",
        theme: "athletics",
        description: "Taught beginner lessons and worked weekend guard shifts.",
      },
      {
        role: "Summer Volunteer",
        org: "SickKids",
        theme: "service",
        description: "Four-week summer placement supporting family services.",
        relatedOpportunityIds: [7],
      },
    ],
    awards: [],
    acceptedSchoolIds: ["mcgill", "uoft", "mcmaster"],
    attendingSchoolId: "mcgill",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "hannah-kim",
    name: "Hannah Kim",
    major: "Public Policy",
    gradYear: 2024,
    location: "Vancouver, BC",
    curriculum: "BC Dogwood + 5 AP",
    stats: [{ label: "Average", value: "95%" }],
    themes: ["leadership", "arts"],
    extracurriculars: [
      {
        role: "Member",
        org: "BC Youth Parliament",
        theme: "leadership",
        description:
          "Two sessions; sponsored a private member's resolution on transit passes for students.",
        relatedOpportunityIds: [93],
      },
      {
        role: "Video Creator",
        org: "Policy Explainers Channel",
        theme: "leadership",
        description: "Short explainer videos on local policy questions; competition entrant.",
        relatedOpportunityIds: [45],
      },
      {
        role: "Op-Ed Writer",
        org: "Student Essay Contests",
        theme: "arts",
        description: "Published entries on housing and education policy.",
        relatedOpportunityIds: [48],
      },
    ],
    awards: ["Fraser Institute Essay Contest — Honourable Mention (2023)"],
    acceptedSchoolIds: ["uoft", "ubc", "princeton"],
    attendingSchoolId: "uoft",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "diego-ramirez",
    name: "Diego Ramírez",
    major: "Public Policy",
    gradYear: 2025,
    location: "Kamloops, BC",
    curriculum: "BC Dogwood",
    stats: [{ label: "Average", value: "91%" }],
    themes: ["leadership", "service"],
    extracurriculars: [
      {
        role: "Member",
        org: "City Youth Advisory Council",
        theme: "leadership",
        description: "Advised council on a skatepark renewal and youth transit fares.",
      },
      {
        role: "Coordinator",
        org: "Neighbourhood Food Pantry",
        theme: "service",
        description: "Scheduled volunteers and tracked inventory for a weekly pantry.",
        relatedOpportunityIds: [3],
      },
    ],
    awards: [],
    acceptedSchoolIds: ["sfu", "uvic", "queens"],
    attendingSchoolId: "sfu",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "chloe-nguyen",
    name: "Chloe Nguyen",
    major: "Biology",
    gradYear: 2025,
    location: "Burnaby, BC",
    curriculum: "BC Dogwood + 4 AP",
    stats: [{ label: "Average", value: "96%" }],
    themes: ["stem"],
    extracurriculars: [
      {
        role: "Olympiad Competitor",
        org: "Canadian Biology Olympiad",
        theme: "stem",
        description: "National exam qualifier in grade 11.",
        relatedOpportunityIds: [104],
      },
      {
        role: "Science Fair Medalist",
        org: "Canada-Wide Science Fair",
        theme: "stem",
        description: "Silver medal for a project on microplastics in local streams.",
        relatedOpportunityIds: [12],
      },
      {
        role: "Volunteer",
        org: "Aquarium Marine Education",
        theme: "service",
        description: "Weekend touch-tank interpreter for school groups.",
      },
    ],
    awards: ["CWSF Silver Medal (2024)"],
    acceptedSchoolIds: ["ubc", "mcgill", "uoft"],
    attendingSchoolId: "ubc",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "samuel-adeyemi",
    name: "Samuel Adeyemi",
    major: "Biology",
    gradYear: 2023,
    location: "Saskatoon, SK",
    curriculum: "SK Diploma",
    stats: [{ label: "Average", value: "92%" }],
    themes: ["stem", "service"],
    extracurriculars: [
      {
        role: "Garden Lead",
        org: "School EcoClub",
        theme: "service",
        description: "Ran a community vegetable garden donating produce to a shelter kitchen.",
        relatedOpportunityIds: [226],
      },
      {
        role: "Lab Volunteer",
        org: "University Ecology Lab",
        theme: "stem",
        description: "Sorted invertebrate samples and entered field data after school.",
      },
    ],
    awards: [],
    acceptedSchoolIds: ["ualberta", "ubc"],
    attendingSchoolId: "ualberta",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "isabella-rossi",
    name: "Isabella Rossi",
    major: "Psychology",
    gradYear: 2024,
    location: "Langley, BC",
    curriculum: "BC Dogwood",
    stats: [{ label: "Average", value: "93%" }],
    themes: ["service", "arts"],
    extracurriculars: [
      {
        role: "Peer Support Lead",
        org: "Wellness Club",
        theme: "service",
        description: "Trained peer listener; organized exam-season de-stress events.",
      },
      {
        role: "Editor",
        org: "Mental-Health Zine",
        theme: "arts",
        description: "Curated student art and writing about wellbeing, printed each semester.",
      },
      {
        role: "In-School Mentor",
        org: "Big Brothers Big Sisters",
        theme: "service",
        description: "Weekly lunch mentoring with an elementary student for two years.",
        relatedOpportunityIds: [63],
      },
    ],
    awards: [],
    acceptedSchoolIds: ["sfu", "uvic", "ubc"],
    attendingSchoolId: "sfu",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "tyler-whitecloud",
    name: "Tyler Whitecloud",
    major: "Psychology",
    gradYear: 2025,
    location: "Prince George, BC",
    curriculum: "BC Dogwood + 2 AP",
    stats: [{ label: "Average", value: "90%" }],
    themes: ["service", "athletics"],
    extracurriculars: [
      {
        role: "Team Captain",
        org: "Cross-Country",
        theme: "athletics",
        description: "Zone champion team; led junior training runs.",
      },
      {
        role: "Camp Counsellor",
        org: "Summer Rec Program",
        theme: "service",
        description: "Two summers leading activities for kids aged 8–11.",
      },
    ],
    awards: ["Zone Cross-Country Champions (2024)"],
    acceptedSchoolIds: ["uvic", "ualberta"],
    attendingSchoolId: "uvic",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "olivia-bennett",
    name: "Olivia Bennett",
    major: "Law",
    gradYear: 2024,
    location: "West Vancouver, BC",
    curriculum: "IB Diploma",
    stats: [{ label: "IB", value: "42/45" }],
    themes: ["leadership", "arts"],
    extracurriculars: [
      {
        role: "Captain",
        org: "Mock Trial Team",
        theme: "leadership",
        description: "Provincial semifinalists; argued lead counsel both years.",
      },
      {
        role: "Essay Competitor",
        org: "John Locke Institute (Law)",
        theme: "arts",
        description: "Commended entry on jury trials and social media.",
        relatedOpportunityIds: [47],
      },
      {
        role: "Coach",
        org: "Junior Debate",
        theme: "service",
        description: "Ran weekly practice rounds for the grade 9 team.",
      },
    ],
    awards: ["Mock Trial Provincial Semifinalist (2024)"],
    acceptedSchoolIds: ["uoft", "mcgill", "queens", "harvard"],
    attendingSchoolId: "uoft",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "ibrahim-yusuf",
    name: "Ibrahim Yusuf",
    major: "Law",
    gradYear: 2025,
    location: "Toronto, ON",
    curriculum: "OSSD",
    stats: [{ label: "Average", value: "94%" }],
    themes: ["leadership", "service"],
    extracurriculars: [
      {
        role: "Founder",
        org: "Know-Your-Rights Workshops",
        theme: "service",
        description:
          "Plain-language sessions on tenant and employment rights, run with a legal-aid clinic.",
      },
      {
        role: "Delegate",
        org: "CAHSMUN",
        theme: "leadership",
        description: "Legal committee delegate; best position paper.",
        relatedOpportunityIds: [36],
      },
      {
        role: "Competitor",
        org: "Policy Video Competition",
        theme: "leadership",
        description: "Category winner with a video on youth court diversion.",
        relatedOpportunityIds: [45],
      },
    ],
    awards: ["LegalEagleBee Category Winner (2024)"],
    acceptedSchoolIds: ["uoft", "queens", "western"],
    attendingSchoolId: "queens",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "zoe-macdonald",
    name: "Zoe MacDonald",
    major: "Political Science",
    gradYear: 2023,
    location: "Victoria, BC",
    curriculum: "BC Dogwood + 3 AP",
    stats: [{ label: "Average", value: "91%" }],
    themes: ["leadership", "arts"],
    extracurriculars: [
      {
        role: "Member",
        org: "BC Youth Parliament",
        theme: "leadership",
        description: "Committee chair in her second session.",
        relatedOpportunityIds: [93],
      },
      {
        role: "Campaign Volunteer",
        org: "Municipal Election",
        theme: "leadership",
        description: "Door-knocking and data entry for a council campaign.",
      },
      {
        role: "Host",
        org: "Civics Podcast",
        theme: "arts",
        description: "Interviewed local officials in a 15-episode student podcast.",
      },
    ],
    awards: [],
    acceptedSchoolIds: ["uvic", "sfu", "mcgill"],
    attendingSchoolId: "uvic",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    id: "arnav-gupta",
    name: "Arnav Gupta",
    major: "Physics",
    gradYear: 2025,
    location: "Richmond, BC",
    curriculum: "BC Dogwood + 6 AP",
    stats: [
      { label: "Average", value: "97%" },
      { label: "SAT", value: "1540" },
    ],
    themes: ["stem"],
    extracurriculars: [
      {
        role: "Exam Competitor",
        org: "CAP Physics Prize",
        theme: "stem",
        description: "School's top score two years running; national honour roll.",
        relatedOpportunityIds: [103],
      },
      {
        role: "Rocketry Lead",
        org: "Aerospace Club",
        theme: "stem",
        description: "Designed and flew model rockets with altimeter data analysis.",
      },
      {
        role: "Tutor",
        org: "Peer Physics Program",
        theme: "service",
        description: "Drop-in help sessions for Physics 11 students twice a week.",
      },
    ],
    awards: ["CAP Prize Exam National Honour Roll (2024)"],
    acceptedSchoolIds: ["ubc", "uoft", "mit", "stanford", "waterloo"],
    attendingSchoolId: "mit",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    verified: true,
    consent: true,
  },
  {
    id: "emma-fontaine",
    name: "Emma Fontaine",
    major: "Physics",
    gradYear: 2024,
    location: "Montréal, QC",
    curriculum: "CEGEP DEC — Pure & Applied Science",
    stats: [{ label: "R-score", value: "35.1" }],
    themes: ["stem", "arts"],
    extracurriculars: [
      {
        role: "Astrophotographer",
        org: "Astronomy Club",
        theme: "arts",
        description: "Ran the club's imaging nights and published a yearly photo calendar.",
      },
      {
        role: "Science Fair Competitor",
        org: "Expo-Sciences / CWSF",
        theme: "stem",
        description: "Provincial finalist with a spectroscopy project on streetlight pollution.",
        relatedOpportunityIds: [12],
      },
    ],
    awards: ["Expo-Sciences Provincial Finalist (2023)"],
    acceptedSchoolIds: ["mcgill", "uoft"],
    attendingSchoolId: "mcgill",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: true,
  },
  {
    // Consent-gate proof: this entry must never render anywhere on the site.
    id: "no-consent-check",
    name: "Withheld Student",
    major: "Undeclared",
    gradYear: 2025,
    location: "Vancouver, BC",
    curriculum: "BC Dogwood",
    stats: [],
    themes: ["stem"],
    extracurriculars: [],
    awards: [],
    acceptedSchoolIds: ["ubc"],
    attendingSchoolId: "ubc",
    sourceVideoUrl: "https://www.youtube.com/@bcinitiativessociety",
    consent: false,
  },
];

/** The consent gate. Non-consenting entries never leave this module. */
export const profiles: Profile[] = allProfiles.filter((p) => p.consent === true);

export const getProfile = (id: string) => profiles.find((p) => p.id === id);

export const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

/** Checkbox options for the Major filter — derived from the data, grows with it. */
export const majorOptions = [...new Set(profiles.map((p) => p.major))]
  .sort()
  .map((m) => ({ value: slugify(m), label: m }));
