export type UsTier = "ivy" | "top-private" | "uc" | "top-public";

export interface School {
  id: string;
  name: string;
  short: string; // crest fallback label when no logo image exists, keep <= 3 chars
  logo?: string; // path under public/; missing files fall back to `short` seamlessly
  country: "CA" | "US";
  usTier?: UsTier; // required for US schools so every one lands in a section
}

export const schools: School[] = [
  {
    id: "ubc",
    name: "University of British Columbia",
    short: "UBC",
    logo: "/schools/ubc.png",
    country: "CA",
  },
  {
    id: "sfu",
    name: "Simon Fraser University",
    short: "SFU",
    logo: "/schools/sfu.png",
    country: "CA",
  },
  {
    id: "uvic",
    name: "University of Victoria",
    short: "UV",
    logo: "/schools/uvic.png",
    country: "CA",
  },
  {
    id: "uoft",
    name: "University of Toronto",
    short: "UT",
    logo: "/schools/uoft.png",
    country: "CA",
  },
  {
    id: "mcgill",
    name: "McGill University",
    short: "McG",
    logo: "/schools/mcgill.png",
    country: "CA",
  },
  {
    id: "waterloo",
    name: "University of Waterloo",
    short: "UW",
    logo: "/schools/waterloo.png",
    country: "CA",
  },
  {
    id: "harvard",
    name: "Harvard University",
    short: "HU",
    logo: "/schools/harvard.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "stanford",
    name: "Stanford University",
    short: "SU",
    logo: "/schools/stanford.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "queens",
    name: "Queen's University",
    short: "QU",
    logo: "/schools/queens.png",
    country: "CA",
  },
  {
    id: "mcmaster",
    name: "McMaster University",
    short: "McM",
    logo: "/schools/mcmaster.png",
    country: "CA",
  },
  {
    id: "western",
    name: "Western University",
    short: "UWO",
    logo: "/schools/western.png",
    country: "CA",
  },
  {
    id: "ualberta",
    name: "University of Alberta",
    short: "UA",
    logo: "/schools/ualberta.jpg",
    country: "CA",
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    short: "MIT",
    logo: "/schools/mit.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "princeton",
    name: "Princeton University",
    short: "PU",
    logo: "/schools/princeton.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "yale",
    name: "Yale University",
    short: "Y",
    logo: "/schools/yale.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "penn",
    name: "University of Pennsylvania",
    short: "UP",
    logo: "/schools/penn.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "duke",
    name: "Duke University",
    short: "DU",
    logo: "/schools/duke.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "columbia",
    name: "Columbia University",
    short: "CU",
    logo: "/schools/columbia.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "georgetown",
    name: "Georgetown University",
    short: "GU",
    logo: "/schools/georgetown.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "washu",
    name: "Washington University in St. Louis",
    short: "WU",
    logo: "/schools/washu.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "ucla",
    name: "UCLA",
    short: "UCL",
    logo: "/schools/ucla.png",
    country: "US",
    usTier: "uc",
  },
  {
    id: "cornell",
    name: "Cornell University",
    short: "COR",
    logo: "/schools/cornell.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "michigan",
    name: "University of Michigan",
    short: "UM",
    logo: "/schools/michigan.png",
    country: "US",
    usTier: "top-public",
  },
  {
    id: "usc",
    name: "University of Southern California",
    short: "USC",
    logo: "/schools/usc.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    short: "GT",
    logo: "/schools/gatech.png",
    country: "US",
    usTier: "top-public",
  },
  {
    id: "uva",
    name: "University of Virginia",
    short: "UVA",
    logo: "/schools/uva.png",
    country: "US",
    usTier: "top-public",
  },
  {
    id: "utaustin",
    name: "University of Texas at Austin",
    short: "UTA",
    logo: "/schools/utaustin.png",
    country: "US",
    usTier: "top-public",
  },
  {
    id: "ucirvine",
    name: "UC Irvine",
    short: "UCI",
    logo: "/schools/ucirvine.png",
    country: "US",
    usTier: "uc",
  },
  {
    id: "ucsd",
    name: "UC San Diego",
    short: "SD",
    logo: "/schools/ucsd.png",
    country: "US",
    usTier: "uc",
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    short: "NEU",
    logo: "/schools/northeastern.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "brown",
    name: "Brown University",
    short: "BR",
    logo: "/schools/brown.png",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "dartmouth",
    name: "Dartmouth College",
    short: "DAR",
    logo: "/schools/dartmouth.jpg",
    country: "US",
    usTier: "ivy",
  },
  {
    id: "caltech",
    name: "California Institute of Technology",
    short: "CIT",
    logo: "/schools/caltech.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "ucberkeley",
    name: "UC Berkeley",
    short: "CAL",
    logo: "/schools/ucberkeley.png",
    country: "US",
    usTier: "uc",
  },
  {
    id: "uchicago",
    name: "University of Chicago",
    short: "UC",
    logo: "/schools/uchicago.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    short: "VU",
    logo: "/schools/vanderbilt.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "emory",
    name: "Emory University",
    short: "EU",
    logo: "/schools/emory.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    short: "CMU",
    logo: "/schools/cmu.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "rice",
    name: "Rice University",
    short: "RU",
    logo: "/schools/rice.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "bu",
    name: "Boston University",
    short: "BU",
    logo: "/schools/bu.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    short: "NU",
    logo: "/schools/northwestern.png",
    country: "US",
    usTier: "top-private",
  },
  {
    id: "ucsb",
    name: "UC Santa Barbara",
    short: "UCSB",
    logo: "/schools/ucsb.png",
    country: "US",
    usTier: "uc",
  },
  {
    id: "ucdavis",
    name: "UC Davis",
    short: "UCD",
    logo: "/schools/ucdavis.png",
    country: "US",
    usTier: "uc",
  },
  {
    id: "unc",
    name: "UNC Chapel Hill",
    short: "UNC",
    logo: "/schools/unc.png",
    country: "US",
    usTier: "top-public",
  },
  // Logo files not yet added — SchoolCrest falls back to the `short` label.
  {
    id: "york",
    name: "York University",
    short: "YU",
    country: "CA",
  },
  {
    id: "nyu",
    name: "New York University",
    short: "NYU",
    country: "US",
    usTier: "top-private",
  },
];

export const schoolById: Record<string, School> = Object.fromEntries(schools.map((s) => [s.id, s]));

/** Display sections for school pickers (filter panel + match quiz). Purely cosmetic — matching uses ids only. */
export interface SchoolSection {
  label: string;
  schools: School[];
}

export const schoolSections: SchoolSection[] = [
  { label: "Canadian Universities", schools: schools.filter((s) => s.country === "CA") },
  { label: "Ivy League", schools: schools.filter((s) => s.usTier === "ivy") },
  { label: "Top Private Schools", schools: schools.filter((s) => s.usTier === "top-private") },
  { label: "UC Schools", schools: schools.filter((s) => s.usTier === "uc") },
  { label: "Top Public Schools", schools: schools.filter((s) => s.usTier === "top-public") },
];
